# - hosts: test-ansible
#   tasks:
#     - name: create file
#       copy:
#         dest: /home/ubuntu/index.html
#         content: <h1>Voltando</h1>

#     - name: create server
#       shell: "nohup busybox httpd -f -p 8080 &"

- hosts: test-ansible
  tasks:
    - name: Install python and virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
